repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.4.0"
  hooks:
  - id: check-ast
  - id: check-toml
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: trailing-whitespace
