# Builds and deploys documentation for the package

name: document

# Allows this Action to be called by other Actions or through GitHub
on: [workflow_call, workflow_dispatch]

permissions:
  contents: write
  pull-requests: write

jobs:

  build_and_deploy_documentation:
    name: Build and deploy docs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Setup PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: 3.x

    - name: Install dependencies
      shell: bash
      run: pdm install -v && pdm info

    - name: Build documentation with MkDocs
      run: pdm run mkdocs build

    - name: Deploy documentation to GitHub Pages
      run: pdm run mkdocs gh-deploy --force --clean --verbose
