name: validate_codecov

on:
  pull_request:
    paths: [codecov.yml]
  push:
    branches: [main]

jobs:
  validate-codecov-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Validate codecov configuration
        run: curl -sSL --fail-with-body --data-binary @codecov.yml https://codecov.io/validate
