# Automatically updates dependency versions using dependabot.

version: 2
updates:

# Maintains dependencies for Python via `pip`
- package-ecosystem: pip
  directory: "/"
  # Always updates to a newer version. If you want a less aggressive strategy, 
  # change the value to "increase-if-necessary"
  versioning-strategy: increase
  schedule:
    interval: weekly
    time: "5:00"

# Maintains dependencies for GitHub Actions
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "weekly"
    time: "6:00"