# Builds package and creates environment

name: build

on: workflow_call

jobs:

  build_package:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{"{{"}} matrix.python-version {{"}}"}}

    - name: Setup PDM
      uses: pdm-project/setup-pdm@v2
      id: setup-pdm
      with:
        python-version: ${{"{{"}} matrix.python-version {{"}}"}}
  
    - name: Check output
      shell: bash
      run: |
        echo ${{"{{"}} steps.setup-pdm.outputs.pdm-bin {{"}}"}}
        echo ${{"{{"}} steps.setup-pdm.outputs.pdm-version {{"}}"}}
        echo ${{"{{"}} steps.setup-pdm.outputs.python-path {{"}}"}}
        echo ${{"{{"}} steps.setup-pdm.outputs.python-version {{"}}"}}

    - name: Install dependencies
      shell: bash
      run: pdm install -v && pdm info
