# Creates a code coverage badge for the README.md file

name: Coverage

on: [push, pull_request, workflow_call]

permissions:
    contents: write
    pull-requests: write
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3
  
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Setup PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: 3.x

    - name: Install dependencies
      shell: bash
      run: pdm install -v && pdm info

    - name: Test with pytest
      run: pdm run -v pytest tests --cov --cov-report=html:coverage_re

    - name: Coverage Bagdge
      uses: tj-actions/coverage-badge-py@v1.8
      with:
        output: docs/coverage/coverage.svg

    - name: Publish coverage report to coverage-badge branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: coverage-badge
        folder: docs/coverage
