# Merges branches on GitHub
# This action is currently untested

name: merge

# Allows this Action to be called by other Actions or through GitHub
on: [workflow_call, workflow_dispatch]

permissions:
  contents: write
  pull-requests: write

jobs:

  merge_branches:
    name: merge branches
    runs-on: ubuntu-latest

    steps:
    - name: get repository
      uses: actions/checkout@v3

    - name: create pull request
      id: open-pr
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: ${{ github.event.repository.default_branch }}
        pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
        pr_body: "Automated Pull Request"

    - name: enable automerge
      if: steps.open-pr.outputs.pr_number != ''
      run: gh pr merge --merge --auto "1"
      env:
        GH_TOKEN: ${{ secrets.PAT }}
