# Action for securely publishing the package on PyPI

# This code is adapted  from the model Action in the PDM documentation:
# https://pdm.fming.dev/latest/usage/publish/

# This Action does not build the project - it simply publishes the contents of
# the contents of the ".pdm-build" folder.

name: publish

# Allows this Action to be called by other Actions or through GitHub
on: [workflow_call, workflow_dispatch]

jobs:
  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
    # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup PDM
      uses: pdm-project/setup-pdm@v3

    - name: Publish to PyPI
      run: pdm publish
