# Releases a new version on GitHub whenever a commit message matches the
# version format (e.g. "v0.1.2"). For further documentation on this Action, see:
# https://github.com/marketplace/actions/github-create-tag-release

name: GitHub Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:

  release:
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub release
        uses: Roang-zero1/github-create-release-action@v3
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}