# Releases a new version on GitHub whe a commit message is a version number.

# To trigger this Action, the commit message must match the version format 
# (e.g. "v0.1.2"). For further documentation on this Action, see:
# https://github.com/marketplace/actions/github-create-tag-release

name: GitHub Release

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: write
  pull-requests: write

jobs:

  release:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Generate GitHub Release
      uses: lsegal/github-release-from-changelog-action@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
